### ISSUE TITLE
Forking or contributing?

### ISSUE THREAD

**Issue by bradobro** [m-dressler/cli#1]
Hi Mauritz,

I like what you've done here! 

I'm thinking about playing with the code a bit, improvising on what you've done so far. I don't want to start another project if you think this is a library you want to keep small but bring to a 1.x.x release and are interested in hearing contribution proposals. On the other hand, if it's a project to support your personal needs mostly, then I can just keep my work on a fork.

Can you give me your thoughts on that? Hope you are well!

--Brad Olson

**Comment by m-dressler** [comment]
Hey Brad, created this for personal needs but would definitely have fun in bringing this to a more generic/stable point, even if the audience is tiny. So definitely shoot over any proposals if you have any!

**Comment by bradobro** [comment]
Thanks for your reply, Mauritz. I've enjoyed reading your code. Not sure if I'll come up with anything--I have my own attempt at a lightweight cli lib on jsr I cobbled out before I found yours. I might riff on that for a bit, I'll see. Thanks for sharing your code! I like your succinct approach.
